name: Repo Actions

on:
  push:
    branches: [main] # Define any other protected branches
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '21 13 * * 2'

jobs:
  run-unit-tests:
    name: Run Unit Tests ${{ matrix.python-version }}
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run pytest, Python version ${{ matrix.python-version }}
        uses: GenapsysInc/internal-actions/reusable-actions/pytest@main
        with:
          python-version: ${{ matrix.python-version }}
          requirements-txt: requirements-test.txt
  static-analysis:
    name: Static Analysis
    uses: GenapsysInc/internal-actions/.github/workflows/static-analysis.yml@main
    with:
      requirements-txt: requirements-test.txt
  check-version:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Run the check-version action
        id: run-check-version
        uses: GenapsysInc/internal-actions/reusable-actions/check-version@main
        with:
          json: src/hyalus/metadata.json
          include-paths: '*.py MANIFEST.in pyproject.toml setup.cfg'
          exclude-paths: 'docs tests conftest.py'
  increment-version:
    name: Increment Version
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.run-increment-version.outputs.new-version }}
    steps:
      - name: Run the increment-version action
        id: run-increment-version
        uses: GenapsysInc/internal-actions/reusable-actions/increment-version@main
        with:
          json: src/hyalus/metadata.json
          protect-tag: true
  codeql:
    name: CodeQL ${{ matrix.language }}
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [python] # Define this
    steps:
      - name: Run CodeQL action with language ${{ matrix.language }}
        uses: GenapsysInc/internal-actions/reusable-actions/codeql@main
        with:
          language: ${{ matrix.language }}
  doc-build:
    name: Documentation Builder
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    needs: increment-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Documentation build and publish
        uses: GenapsysInc/internal-actions/reusable-actions/build-docs@main
        with:
          token: ${{ github.token }}
          build_html: true
          publish_html: ${{ github.event_name == 'push' }}
          warn_as_errors: false
          version: ${{ needs.increment-version.outputs.new-version }}
          api_dirs: src/hyalus tests
          api_exclude: tests/*/data/*.py tests/run/*_dir*/*/*.py
          build_options: -n
